<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 18.10.2018
 * Time: 15:24
 */

namespace app\components\widgets;
use yii\base\Widget;
use app\models\search\ExpertsSearch;

class ListExperts extends Widget
{
    public $order = 'flip';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $searchModel = new ExpertsSearch();
        $dataProvider = $searchModel->search([], [$this->order => SORT_DESC]);

        return $this->render('list-experts', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'order' => $this->order,
        ]);
//        parent::run(); // TODO: Change the autogenerated stub
    }
}