<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 10.10.2018
 * Time: 20:47
 */

namespace app\models\helpers;

use app\components\jobs\RatingExpertJob;
use app\components\jobs\RatingProjectJob;
use yii\behaviors\TimestampBehavior;

class ProjectData extends \app\models\ProjectData
{
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                /*'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),*/
            ],
        ];
    }

    public function getRating()
    {

    }

    public function afterSave($insert, $changedAttributes)
    {
        \Yii::$app->queue->push(
            new RatingExpertJob(['expert_id' => $this->expert_id])
        );
        \Yii::$app->queue->delay(3 * 60)->push(
            new RatingProjectJob(['project_id' => $this->project_id])
        );
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}