<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 10.10.2018
 * Time: 20:47
 */

namespace app\models\helpers;

use app\components\jobs\RatingExpertJob;
use app\components\jobs\RatingProjectJob;
use yii\behaviors\TimestampBehavior;

class ProjectData extends \app\models\ProjectData
{
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                /*'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),*/
            ],
        ];
    }

    public function getRating()
    {

    }

    public function beforeValidate()
    {
        $this->Score = implode('/', [$this->scoreFlip, $this->scoreHold]);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        if(!empty($this->Score)) {
            $data = explode('/', $this->Score);
            if(count($data) == 1) {
                $this->scoreFlip = $this->scoreHold = $this->Score;
            } else {
                $this->scoreFlip = $data[0];
                $this->scoreHold = $data[1];
            }
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
//        \Yii::$app->queue->push(
//            new RatingExpertJob(['expert_id' => $this->expert_id])
//        );
        \Yii::$app->queue/*->delay(3 * 60)*/->push(
            new RatingProjectJob(['project_id' => $this->project_id])
        );
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}